name: student_job_applying
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^0.13.4
  url_launcher: ^6.1.2
  shared_preferences: ^2.0.11
  permission_handler: ^9.0.1
  app_settings: ^4.1.5
  image_picker: ^0.8.5
  rxdart: ^0.27.3
  intl: ^0.17.0
  #UX
  keyboard_dismisser: ^2.0.1
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.0.9
  #UI
  badges: ^2.0.2
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          style: italic
